version: '3'

services:
  warehouse:
    image: postgres:13
    container_name: warehouse
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}" ]
      interval: 5s
      retries: 5
    restart: always
    volumes:
      - ./assets/db_setup.sql:/docker-entrypoint-initdb.d/1-init.sql
    ports:
      - "5432:${POSTGRES_PORT}"
  pipelinerunner:
    depends_on:
      - warehouse
    container_name: pipelinerunner
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      WAREHOUSE_USER: ${POSTGRES_USER}
      WAREHOUSE_PASSWORD: ${POSTGRES_PASSWORD}
      WAREHOUSE_DB: ${POSTGRES_DB}
      WAREHOUSE_HOST: ${POSTGRES_HOST}
      WAREHOUSE_PORT: ${POSTGRES_PORT}
